parameters:
    bangpound_castle.types:
        Bangpound.Bundle.TwitterStreamingBundle.CouchDocument.AtomEntry: "kal3a: Twitter"
        Rshief.MigrationBundle.CouchDocument.CollectorAtomEntry: Twitterminer
        Rshief.MigrationBundle.CouchDocument.AtomEntry: VBulletin
        Bangpound.Bundle.CastleBundle.CouchDocument.AtomEntry: Castle
        Bangpound.Bundle.PubsubBundle.CouchDocument.AtomEntry: "kal3a: RSS / Atom"

services:
#    bangpound_castle.example:
#        class: %bangpound_castle.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
